### PR TITLE
Updated to v1.4.0, Added Delete ISO and Github Link 

### PR DESCRIPTION
**Pull request by blahpr**
Updated: to v1.4.0
Added: Delete ISO After Completion Checkbox in Settings under Options.
Added Github Link 
Here -> https://github.com/blahpr/Iso2God/releases/latest
@blahpr

### CODE REVIEW

**Comment by r4dius** [comment]
Hi, I've been working on a test branch some time ago with this feature, some gui lifting and other stuff I don't even remember, I'll be releasing it when I can't work on it again.

**Comment by r4dius** [comment]
Ok I totally missunderstood this feature, I mixed it up with the "keep / delete converted iso" that's already in the release and not in my tests 🤣, I'll be adding your change and maybe add a warning popup to tell it will erase stuff

**Comment by blahpr** [comment]
Dope. im here for making changes. To Code or creating new stuff and helping where and when i can.

**Comment by blahpr** [comment]
> Dope. im here for making changes. To Code or creating new stuff and helping where and when i can.

**Comment by r4dius** [comment]
Added your function to delete the iso in Main.cs, there was some code not used or looked like duplicate I didn't not add,
please let me know if I missed something, looked like it was working on my tests

**Comment by blahpr** [comment]
i synced by accident.

**Comment by blahpr** [comment]
Capture
This is Beautiful my Friend.

**Pull request closed without merging**
